#!/bin/bash
# -------------------------------------------------------------------------------
# MIT License
#
# Copyright (c) 2023 - 2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# -------------------------------------------------------------------------------

# Convenience launch wrapper tool for user-mode on ORNL

setup_env() {
    # setup local env
    module try-load cray-python/3.11.5
    module use /autofs/nccs-svm1_sw/crusher/amdsw/modules
    module try-load omnistat
    export OMNISTAT_CONFIG=${OMNISTAT_DIR}/omnistat/config/omnistat.ornl
}


usage() {
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -h, --help           Show usage info and exit"
    echo "  -interval <value>    Set polling interval (in secs)"
    echo ""
}

# command-line args
interval=60

while [[ $# -gt 0 ]]; do
    case "$1" in
	-h|--help)
	    usage
	    exit 0
	    ;;
	-interval)
	    interval="$2"
	    shift 2
	    ;;
	-*)
	    echo "Unknown option: $1"
	    exit 1
	    ;;
	*)
	    break
	    ;;
    esac
done

setup_env

[ -x "${OMNISTAT_DIR}/omnistat-usermode" ] || { echo "Error: unable to access ${OMNISTAT_DIR}/omnistat-usermode."; exit 1; }
[ -f "${OMNISTAT_CONFIG}" ] || { echo "Error: unable to access runtime config -> ${OMNISTAT_CONFIG}."; exit 1; }

${OMNISTAT_DIR}/omnistat-usermode --start --interval ${interval} --config ${OMNISTAT_CONFIG}



