{
 "title": "Node - RMS",
 "tags": [ "omnistat" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(rocm_num_gpus,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocm_num_gpus{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rocm_version_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage{instance=\"$instance\"}) / count(rocm_utilization_percentage{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage{instance=\"$instance\"}) / count(rocm_vram_used_percentage{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"${instance:text}:$node_exporter_port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "description": "Average 1m Load Average.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"${instance:text}:$node_exporter_port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=\"${instance:text}:$node_exporter_port\"} / node_memory_MemTotal_bytes{instance=\"${instance:text}:$node_exporter_port\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocation Summary",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by (job,instance,jobid) (rmsjob_info{instance=\"$instance\",jobid!=\"\"})",
     "legendFormat": "{{jobid}}"
    }
   ]
  },
  { "title": "GPU - Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GPU Utlization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rocm_utilization_percentage{instance=\"$instance\"})",
     "legendFormat": "GPU ID {{card}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utlization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rocm_vram_used_percentage{instance=\"$instance\"}",
     "legendFormat": "GPU ID {{card}}"
    }
   ]
  },
  { "title": "GPU - Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (card, location) (rocm_temperature_celsius{instance=\"$instance\"}) ",
     "legendFormat": "GPU ID {{card}} ({{location}})"
    }
   ]
  },
  {
   "title": "GPU Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (card, location) (rocm_temperature_memory_celsius{instance=\"$instance\"})",
     "legendFormat": "GPU ID {{card}} ({{location}})"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(rocm_average_socket_power_watts{instance=\"$instance\"}) ",
     "legendFormat": "GPU ID {{card}}"
    }
   ]
  },
  {
   "title": "GPU Clock Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "rocm_sclk_clock_mhz{instance=\"$instance\"}",
     "legendFormat": "GPU ID {{card}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clock Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "rocm_mclk_clock_mhz{instance=\"$instance\"}",
     "legendFormat": "GPU ID {{card}}"
    }
   ]
  },
  { "title": "GPU - RAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Correctable Errors by GPU ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by (card) ({__name__=~\"rocm_ras_.+_correctable_count\",instance=\"$instance\"})",
     "legendFormat": "{{card}}"
    }
   ]
  },
  {
   "title": "Uncorrectable Errors by GPU ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum by (card) ({__name__=~\"rocm_ras_.+_uncorrectable_count\",instance=\"$instance\"})",
     "legendFormat": "{{card}}"
    }
   ]
  },
  {
   "title": "Correctable Errors by Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"rocm_ras_.+_correctable_count\",instance=\"$instance\"})",
     "legendFormat": "{{card}}"
    }
   ]
  },
  {
   "title": "Uncorrectable Errors by Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"rocm_ras_.+_uncorrectable_count\",instance=\"$instance\"})",
     "legendFormat": "{{card}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "CPU 1m Load Average per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "node_load1{instance=\"${instance:text}:$node_exporter_port\"}",
     "legendFormat": "Node: ${instance:text}"
    }
   ]
  },
  {
   "title": "CPU Memory (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum(node_memory_MemAvailable_bytes{instance=\"${instance:text}:$node_exporter_port\"}) / sum(node_memory_MemTotal_bytes{instance=\"${instance:text}:$node_exporter_port\"})) * 100",
     "legendFormat": "Node: ${instance:text}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{instance=\"${instance:text}:$node_exporter_port\"}[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance=\"${instance:text}:$node_exporter_port\"}[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{instance=\"${instance:text}:$node_exporter_port\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"${instance:text}:$node_exporter_port\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_infiniband_port_data_received_bytes_total{instance=\"${instance:text}:$node_exporter_port\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total{instance=\"${instance:text}:$node_exporter_port\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Inventory",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 217 },
     "targets": [
      {
       "expr": "rocm_version_info{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Index",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "timestamp(group by (jobid,user,batchflag,partition,nodes) (rmsjob_info{jobid=~\"^\\\\d+\",instance=\"$instance\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}