{
 "title": "Global - RMS",
 "tags": [ "omnistat" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(rocm_num_gpus)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rocm_num_gpus)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rmsjob_info{jobid=~\"^\\\\d+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Allocated GPUs",
   "type": "stat",
   "description": "Number of GPUs in nodes allocated to active jobs.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage * on (instance) group_left() (rmsjob_info{jobid=~\"^\\\\d+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "description": "Average 1m Load Average.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_load1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count by (jobid) (rmsjob_info{jobid=~\"^\\\\d.+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Number of Allocated GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage * on (instance) group_left() (rmsjob_info{jobid=~\"^\\\\d+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network: Ethernet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Network: Infiniband",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Types",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Driver",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU VBIOS",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 682 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Type to VBIOS Mapping",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 682 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Detailed GPU Versions",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 688 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Index",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11138 },
     "targets": [
      {
       "expr": "timestamp(group by (jobid,user,batchflag,partition,nodes) (rmsjob_info{jobid=~\"^\\\\d+\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Rankings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Occupancy (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1959 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Occupancy (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1959 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2387 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2387 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Characterization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Core vs Memory per Job - Batch (1 min or longer)",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12848 },
     "targets": [
      {
       "expr": "rocm_utilization_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "rocm_vram_used_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(group by (jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Duration Histogram - Batch",
     "type": "histogram",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2866 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(group by (jobid) (rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"}))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg(rocm_utilization_percentage)",
       "legendFormat": "GPU"
      },
      { "expr": "avg(rocm_vram_used_percentage)", "legendFormat": "GPU Memory Capacity" },
      { "expr": "avg(rocm_vram_busy_percentage)", "legendFormat": "GPU Memory Controller Activity" }
     ]
    },
    {
     "title": "GPU Utilization by Node",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 137 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Utlization (%) in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage) * on (instance) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Utlization (%) in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage) * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_celsius) * on (instance) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_celsius) * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_memory_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2869 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(rocm_average_socket_power_watts) ",
       "legendFormat": "Power"
      }
     ]
    },
    {
     "title": "GPU Power per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3214 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Power in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3223 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_average_socket_power_watts)  * on (instance) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Power in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3223 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_average_socket_power_watts)  * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_sclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_mclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 1m Load Average per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1967 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Node: {{instance}}" }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2031 },
     "targets": [
      {
       "expr": "(node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2031 },
     "targets": [
      {
       "expr": "(node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2873 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2961 },
     "targets": [
      {
       "expr": "100 - (sum by (instance) (node_memory_MemAvailable_bytes) / sum by (instance) (node_memory_MemTotal_bytes)) * 100",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO - Disk Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate IO Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2281 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "IO Bandwidth per Node - Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2289 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total[$__rate_interval]))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "IO Bandwidth per Node - Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2289 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total[$__rate_interval]))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Ethernet Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Ethernet Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1970 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1978 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1978 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Infiniband Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Infiniband Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1987 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Received - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1995 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Received - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1995 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2003 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2003 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}