{
 "title": "omnistat-job",
 "tags": [ "omnistat" ],
 "time": { "from": "2024-07-25T22:30:22.858Z", "to": "2024-07-25T22:31:10.238Z" },
 "templating": {
  "list": [
   { "name": "jobid", "label": "SLURM Job ID" },
   { "name": "interval", "label": "Interval", "query": "60s,30s,5s" },
   { "name": "source", "label": "Data Source" }
  ]
 },
 "panels": [
  { "title": "Summary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Utilization Summary",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "GPU Core"
    },
    {
     "expr": "avg(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "GPU Memory"
    }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "max(timestamp(rmsjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Mean GPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Utilization Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "{{card}}"
    }
   ]
  },
  {
   "title": "Max GPU Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "max by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "{{card}}"
    }
   ]
  },
  {
   "title": "Additional GPU telemetry: Utilization, Temperature, Power and Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Card: {{card}}"
      }
     ]
    },
    {
     "title": "GPU Temperature - Die Edge (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_temperature_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Card: {{card}}"
      }
     ]
    },
    {
     "title": "GPU Power (W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_average_socket_power_watts * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Card: {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Engine Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_sclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Card: {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Memory Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_mclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Card: {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Multiple Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution of GPU Utilization Over Time (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "quantile(0.20, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.2 "
      },
      {
       "expr": "quantile(0.5, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Median"
      },
      {
       "expr": "quantile(0.8, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.8"
      },
      {
       "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per Node",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per GPU",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Trace",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rmsjob_annotations{jobid=\"$jobid\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Annotated Regions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(count by (marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (marker) ((rocm_utilization_percentage) * on (instance) group_left(jobid,marker) rmsjob_info{jobid=\"$jobid\"} * on (jobid) group_left(marker) count by (jobid,marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}