{
 "title": "Job - User",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "jobid",
    "label": "Job ID",
    "query": {
     "query": "label_values(rmsjob_info,jobid)"
    }
   },
   { "name": "interval", "label": "Resolution", "query": "0.1s,0.5s,1s,5s,15s,30s,60s" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "Job Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$jobid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "{{batchflag}}"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rocm_num_gpus * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "max(timestamp(rmsjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GPU",
   "type": "stat",
   "description": "Average over time of the average GPU Utilization of all GPUs.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all GPUs in all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "stat",
   "description": "Average over time of the average of GPU Memory utilization of all GPUs.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all GPUs in all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Network Bandwidth (Omnistat)",
   "type": "stat",
   "description": "Aggregate network bandwidth of all nodes. Includes received and transmitted data.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(omnistat_network_rx_bytes{device_class=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"}) + sum(rate(omnistat_network_tx_bytes{device_class=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Ethernet"
    },
    {
     "expr": "sum(rate(omnistat_network_rx_bytes{device_class!=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"}) + sum(rate(omnistat_network_tx_bytes{device_class!=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "High Performance Interconnect"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(omnistat_network_rx_bytes{device_class=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Eth Rx"
    },
    {
     "expr": "sum(rate(omnistat_network_tx_bytes{device_class=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Eth Tx"
    },
    {
     "expr": "sum(rate(omnistat_network_rx_bytes{device_class!=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Other Rx"
    },
    {
     "expr": "sum(rate(omnistat_network_tx_bytes{device_class!=\"net\"}[$__rate_interval]) * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Other Tx"
    }
   ]
  },
  {
   "title": "GPU Usage - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1086 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1086 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1113 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - GPU IDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean GPU Utilization (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1122 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1122 },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "Max GPU Memory Utilization (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1810 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1810 },
     "targets": [
      {
       "expr": "avg by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1818 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - Distribution - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution of GPU Utilization Over Time (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1123 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "quantile(0.20, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.2 "
      },
      {
       "expr": "quantile(0.5, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Median"
      },
      {
       "expr": "quantile(0.8, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.8"
      },
      {
       "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per GPU",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1188 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per GPU",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1188 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Utilization per GPU",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1197 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - Distribution -  Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution of Average Utilization per Node",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1467 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per Node",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1467 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Utilization per Node",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1476 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Telemetry: GPU IDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1125 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (card, location) (rocm_temperature_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}} ({{location}})"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1133 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (card, location) (rocm_temperature_memory_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}} ({{location}})"
      }
     ]
    },
    {
     "title": "GPU Power (W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1141 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_average_socket_power_watts * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Engine Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1149 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_sclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Memory Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1149 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_mclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Reliability, Availability, and Serviceability (RAS) - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPUs with Non-zero Rate of Correctable Errors (errors/min)",
     "type": "timeseries",
     "description": "Only showing GPUs and blocks with errors. A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_umc_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "UMC, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_sdma_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "SDMA, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_gfx_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "GFX, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_mmhub_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "MMHUB, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_pcie_bif_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "PCIE BIF, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_hdp_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "HDP, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_xgmi_wafl_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "XGMI WAFL, {{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPUs with Non-zero Rate of Uncorrectable Errors (errors/min)",
     "type": "timeseries",
     "description": "Only showing GPUs and blocks with errors. A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_umc_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "UMC, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_sdma_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "SDMA, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_gfx_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "GFX, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_mmhub_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "MMHUB, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_pcie_bif_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "PCIE BIF, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_hdp_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "HDP, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_xgmi_wafl_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "XGMI WAFL, {{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth - Ethernet - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Bandwidth - Received (Omnistat)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 922 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_rx_bytes{device_class=\"net\"}[$__rate_interval])) * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Transmitted (Omnistat)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 922 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_tx_bytes{device_class=\"net\"}[$__rate_interval])) * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth - High Performance Interconnect - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "High Performance Interconnect Bandwidth - Received (Omnistat)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 951 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_rx_bytes{device_class!=\"net\"}[$__rate_interval])) * on (instance) rmsjob_info{jobid=\"$jobid\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "High Performance Interconnect Bandwidth - Transmitted (Omnistat)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 951 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_tx_bytes{device_class!=\"net\"}[$__rate_interval])) * on (instance) rmsjob_info{jobid=\"$jobid\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Annotated Regions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2863 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(count by (marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (marker) (avg by (instance) (rocm_utilization_percentage) * on (instance) group_left(jobid,marker) rmsjob_info{jobid=\"$jobid\"} * on (jobid) group_left(marker) count by (jobid,marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Steps - Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Steps",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 978 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))*1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Elapsed Time",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 978 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 107 }
     ]
    },
    {
     "title": "GPU Utilization per Job Step",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 986 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "avg by (jobstep) ((rocm_utilization_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobstep) ((rocm_utilization_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 986 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 108 }
     ]
    },
    {
     "title": "GPU Memory Utilization per Job Step",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 994 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "avg by (jobstep) ((rocm_vram_used_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobstep) ((rocm_vram_used_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 994 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 109 }
     ]
    },
    {
     "title": "GPU Power per Job Step",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1002 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "avg by (jobstep) ((rocm_average_socket_power_watts) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobstep) ((rocm_average_socket_power_watts) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average GPU Power",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1002 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 110 }
     ]
    }
   ]
  }
 ]
}