services:
  prometheus:
    image: victoriametrics/victoria-metrics
    container_name: prometheus
    command:
      - '-httpListenAddr=:9090'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus-data/vicdata/:/victoria-metrics-data
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/json-models/index.json
    volumes:
      - ./grafana:/etc/grafana/provisioning
