services:
  omnistat:
    build:
      dockerfile: Dockerfile
    image: omnistat/load
    container_name: omnistat
    ports:
      - 9090:9090
    environment:
      - DATADIR=${DATADIR:-}
      - MULTIDIR=${MULTIDIR:-}
    volumes:
      - ${DATADIR:-${MULTIDIR:-./data}}:/data

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/json-models/index.json
    volumes:
      - ./grafana:/etc/grafana/provisioning
