services:
  omnistat:
    build:
      dockerfile: Dockerfile
    image: omnistat/load
    container_name: omnistat
    init: true
    ports:
      - 9090:9090
    environment:
      - DATADIR=${DATADIR:-}
      - MULTIDIR=${MULTIDIR:-}
      # Timeout for Victoria Metrics start, in seconds.
      - VICTORIA_TIMEOUT=30
      # Timeout for Victoria Metrics stop and lock release, in seconds.
      - VICTORIA_LOCK_TIMEOUT=30
      # How long to retain samples in the database.
      - VICTORIA_RETENTION_PERIOD=5y
      # Number of days that will be scanned for indexing purposes.
      - INDEX_DAYS=365
      # Indexing query resolution, in seconds.
      - INDEX_STEP=30
      # Number of concurrent indexing queries.
      - INDEX_LIMIT=16
      # Timeout for each indexing query, in seconds.
      - INDEX_QUERY_TIMEOUT=5
    volumes:
      - ${DATADIR:-${MULTIDIR:-./data}}:/data

  proxy:
    image: quay.io/prometheuscommunity/prom-label-proxy
    container_name: proxy
    ports:
      - 9091:9091
    command:
      - "-label=user"
      - "-header-name=X-Grafana-User"
      - "-upstream=http://omnistat:9090"
      - "-insecure-listen-address=:9091"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    attach: false
    environment:
      - GF_LOG_MODE=file
      - GF_LOG_LEVEL=error
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_DEFAULT_THEME=light
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/json-models/index.json
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_DATAPROXY_SEND_USER_HEADER=true
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/json-models:/etc/grafana/provisioning/json-models
