FROM victoriametrics/victoria-metrics

RUN apk update && apk add curl su-exec

COPY loader.sh /usr/local/bin/jobs-data-loader
COPY entrypoint-loader.sh /usr/local/bin/entrypoint

RUN chmod 0777 /usr/local/bin/jobs-data-loader

ENTRYPOINT ["/usr/local/bin/entrypoint"]
