{
 "title": "omniwatch-job",
 "tags": [ "omniwatch" ],
 "time": { "from": "2024-02-22T18:45:00.000Z", "to": "2024-02-22T19:05:00.000Z" },
 "templating": {
  "list": [
   { "name": "jobid", "label": "SLURM Job ID" },
   { "name": "interval", "label": "Interval", "query": "60s,30s,5s" },
   { "name": "source", "label": "Data Source" }
  ]
 },
 "panels": [
  { "title": "Summary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$jobid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(slurmjob_info{jobid=\"$jobid\"})",
     "legendFormat": "{{batchflag}}"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurmjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Utilization Summary",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg(label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card))",
     "legendFormat": "GPU Core"
    },
    {
     "expr": "avg(100 * avg(label_replace({__name__=~\"card(.*)_rocm_vram_used\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_vram_used\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card) / avg(label_replace({__name__=~\"card(.*)_rocm_vram_total\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_vram_total\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card))",
     "legendFormat": "GPU Memory"
    }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurmjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurmjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "max(timestamp(slurmjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Mean GPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Utilization Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "{{card}}"
    }
   ]
  },
  {
   "title": "Max GPU Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "100 * max(label_replace({__name__=~\"card(.*)_rocm_vram_used\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_vram_used\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card) / max(label_replace({__name__=~\"card(.*)_rocm_vram_total\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_vram_total\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "100 * avg(label_replace({__name__=~\"card(.*)_rocm_vram_used\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_vram_used\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card) / max(label_replace({__name__=~\"card(.*)_rocm_vram_total\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_vram_total\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "{{card}}"
    }
   ]
  },
  {
   "title": "Additional GPU telemetry: Utilization, Temperature, Power and Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "GPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Temperature - Die Edge (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_temp_die_edge\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_temp_die_edge\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_avg_pwr\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_avg_pwr\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Frequency - Engine Clock (MHz)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_sclk_clock_mhz\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_sclk_clock_mhz\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Frequency - Memory Clock (MHz)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_mclk_clock_mhz\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_mclk_clock_mhz\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (card)",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  { "title": "Multiple Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Distribution of GPU Utilization Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "quantile(0.20, (label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"})) ",
     "legendFormat": "Quantile 0.2 "
    },
    {
     "expr": "quantile(0.5, (label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"})) ",
     "legendFormat": "Median"
    },
    {
     "expr": "quantile(0.8, (label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"})) ",
     "legendFormat": "Quantile 0.8"
    },
    {
     "expr": "avg((label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Distribution of Average Utilization per Node",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Average Utilization per GPU",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\") * on (instance) group_left() slurmjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true
  },
  {
   "title": "Annotated Regions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "timestamp(count by (marker) (slurmjob_annotations{jobid=\"$jobid\"} > 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (marker) ((label_replace({__name__=~\"card(.*)_rocm_utilization\"}, \"card\", \"$1\", \"__name__\", \"card(.*)_rocm_utilization\")) * on (instance) group_left(jobid,marker) slurmjob_info{jobid=\"$jobid\"} * on (jobid) group_left(marker) count by (jobid,marker) (slurmjob_annotations{jobid=\"$jobid\"} > 0))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}