{
 "title": "Global - Standalone",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(rocm_num_gpus)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rocm_num_gpus)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "description": "Average 1m Load Average.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_load1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network: Ethernet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Network: Infiniband",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Types",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1124 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Driver",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1124 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU VBIOS",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1792 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Type to VBIOS Mapping",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1792 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Detailed GPU Versions",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1798 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "GPU - Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 289 },
     "targets": [
      {
       "expr": "avg(rocm_utilization_percentage)",
       "legendFormat": "GPU"
      },
      { "expr": "avg(rocm_vram_used_percentage)", "legendFormat": "GPU Memory Capacity" },
      { "expr": "avg(rocm_vram_busy_percentage)", "legendFormat": "GPU Memory Controller Activity" }
     ]
    },
    {
     "title": "GPU Utilization by Node",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 946 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1130 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1148 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_memory_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(rocm_average_socket_power_watts) ",
       "legendFormat": "Power"
      }
     ]
    },
    {
     "title": "GPU Power per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 585 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_sclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 568 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_mclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Reliability, Availability, and Serviceability (RAS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes with Non-zero Rate of Correctable Errors (errors/min)",
     "type": "timeseries",
     "description": "Aggregating all RAS events in each node. Only showing blocks/nodes with errors. A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (instance) (delta(rocm_ras_umc_correctable_count[1m])) > 0",
       "legendFormat": "UMC: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_sdma_correctable_count[1m])) > 0",
       "legendFormat": "SDMA: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_gfx_correctable_count[1m])) > 0",
       "legendFormat": "GFX: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_mmhub_correctable_count[1m])) > 0",
       "legendFormat": "MMHUB: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_pcie_bif_correctable_count[1m])) > 0",
       "legendFormat": "PCIE BIF: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_hdp_correctable_count[1m])) > 0",
       "legendFormat": "HDP: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_xgmi_wafl_correctable_count[1m])) > 0",
       "legendFormat": "XGMI WAFL: {{instance}}"
      }
     ]
    },
    {
     "title": "Nodes with Non-zero Rate of Uncorrectable Errors (errors/min)",
     "type": "timeseries",
     "description": "Aggregating all RAS events in each node. Only showing blocks/nodes with errors.  A panel with \"No data\" indicates no errors have been reported during the selected time window.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by (instance) (delta(rocm_ras_umc_uncorrectable_count[1m])) > 0",
       "legendFormat": "UMC: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_sdma_uncorrectable_count[1m])) > 0",
       "legendFormat": "SDMA: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_gfx_uncorrectable_count[1m])) > 0",
       "legendFormat": "GFX: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_mmhub_uncorrectable_count[1m])) > 0",
       "legendFormat": "MMHUB: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_pcie_bif_uncorrectable_count[1m])) > 0",
       "legendFormat": "PCIE BIF: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_hdp_uncorrectable_count[1m])) > 0",
       "legendFormat": "HDP: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_xgmi_wafl_uncorrectable_count[1m])) > 0",
       "legendFormat": "XGMI WAFL: {{instance}}"
      }
     ]
    },
    {
     "title": "History of Correctable Errors per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_correctable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "History of Uncorrectable Errors per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_uncorrectable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes with Correctable Errors",
     "type": "table",
     "description": "A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_correctable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes with Uncorrectable Errors",
     "type": "table",
     "description": "A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_uncorrectable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 1m Load Average per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3077 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Node: {{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3983 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4071 },
     "targets": [
      {
       "expr": "100 - (sum by (instance) (node_memory_MemAvailable_bytes) / sum by (instance) (node_memory_MemTotal_bytes)) * 100",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO - Disk Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate IO Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3391 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "IO Bandwidth per Node - Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3399 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total[$__rate_interval]))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "IO Bandwidth per Node - Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3399 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total[$__rate_interval]))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Ethernet Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Ethernet Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Infiniband Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Infiniband Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3097 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  }
 ]
}