{
 "title": "ras-summary",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Summary of Hosts with Non-zero Rate of Correctable Errors (errors/min)",
   "type": "timeseries",
   "description": "Aggregating all RAS events in each node. Only showing blocks/nodes with errors. A panel with \"No data\" indicates no errors have been reported during the selected time window.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (delta(rocm_ras_umc_correctable_count[1m])) > 0",
     "legendFormat": "UMC: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_sdma_correctable_count[1m])) > 0",
     "legendFormat": "SDMA: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_gfx_correctable_count[1m])) >0",
     "legendFormat": "GFX: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_mmhub_correctable_count[1m])) >0",
     "legendFormat": "MMHUB: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_pcie_bif_correctable_count[1m])) >0",
     "legendFormat": "PCIE BIF: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_hdp_correctable_count[1m])) >0",
     "legendFormat": "HDP: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_xgmi_wafl_correctable_count[1m])) >0",
     "legendFormat": "XGMI WAFL: {{instance}}"
    }
   ]
  },
  {
   "title": "Summary of Hosts with Non-zero Rate of Uncorrectable Errors (errors/min)",
   "type": "timeseries",
   "description": "Aggregating all RAS events in each node. Only showing blocks/nodes with errors.  A panel with \"No data\" indicates no errors have been reported during the selected time window.\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (delta(rocm_ras_umc_uncorrectable_count[1m])) >0",
     "legendFormat": "UMC: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_sdma_uncorrectable_count[1m])) >0",
     "legendFormat": "SDMA: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_gfx_uncorrectable_count[1m])) >0",
     "legendFormat": "GFX: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_mmhub_uncorrectable_count[1m])) >0",
     "legendFormat": "MMHUB: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_pcie_bif_uncorrectable_count[1m])) >0",
     "legendFormat": "PCIE BIF: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_hdp_uncorrectable_count[1m])) >0",
     "legendFormat": "HDP: {{instance}}"
    },
    {
     "expr": "sum by (instance) (delta(rocm_ras_xgmi_wafl_uncorrectable_count[1m])) >0",
     "legendFormat": "XGMI WAFL: {{instance}}"
    }
   ]
  },
  {
   "title": "History of Correctable Errors per Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_correctable_count\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uncorrectable Errors Logged per Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_uncorrectable_count\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hosts with Non-zero Correctable Errors",
   "type": "table",
   "description": "A panel with \"No data\" indicates no errors have been reported during the selected time window.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_correctable_count\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hosts with Uncorrectable Errors",
   "type": "table",
   "description": "A panel with \"No data\" indicates no errors have been reported during the selected time window.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_uncorrectable_count\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}