{
 "title": "rms-global",
 "tags": [ "omnistat" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Active Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rmsjob_info{jobid=~\"^\\\\d+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active Batch Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Number of Jobs Running During Timeframe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count by (jobid) (rmsjob_info{jobid=~\"^\\\\d.+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active GPUs",
   "type": "stat",
   "description": "Number of GPUs in nodes allocated to active jobs.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage * on (instance) group_left() (rmsjob_info{jobid=~\"^\\\\d+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Models",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Omnistat Schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Driver Version",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU VBIOS Version",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Rankings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Occupancy (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 4671 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Occupancy (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 5, "x": 5, "y": 4671 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 7, "x": 10, "y": 4671 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 4671 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU 1m Load Average (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5312 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (user,jobid) (node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Index",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4672 },
     "targets": [
      {
       "expr": "timestamp(group by (jobid,user,batchflag,partition,nodes) (rmsjob_info{jobid=~\"^\\\\d+\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Characterization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Core vs Memory per Job - Batch (1 min or longer)",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6382 },
     "targets": [
      {
       "expr": "rocm_utilization_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "rocm_vram_used_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(group by (jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Duration Histogram - Batch",
     "type": "histogram",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6383 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(group by (jobid) (rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"}))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 556 },
     "targets": [
      {
       "expr": "avg(rocm_utilization_percentage)",
       "legendFormat": "GPU"
      },
      { "expr": "avg(rocm_vram_used_percentage)", "legendFormat": "GPU Memory Capacity" },
      { "expr": "avg(rocm_vram_busy_percentage)", "legendFormat": "GPU Memory Controller Activity" }
     ]
    },
    {
     "title": "GPU Utilization by Node",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 961 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Utlization (%) in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 970 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage) * on (instance) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Utlization (%) in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 970 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage) * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1837 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2139 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_celsius) * on (instance) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2139 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_celsius) * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "GPU HBM Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2148 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_hbm_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 558 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(rocm_average_socket_power_watts) ",
       "legendFormat": "Power"
      }
     ]
    },
    {
     "title": "GPU Power per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 725 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Power in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 734 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_average_socket_power_watts)  * on (instance) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Power in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 734 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_average_socket_power_watts)  * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_sclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_mclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Throttling Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Throttling Events per 1m",
     "type": "timeseries",
     "description": "Aggregating all throttling events in a node.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 939 },
     "targets": [
      {
       "expr": "sum by (instance) (delta(rocm_throttle_events[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "# of Throttling Events per Node",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 948 },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_throttle_events)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 1m Load Average per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 669 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Node: {{instance}}" }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 685 },
     "targets": [
      {
       "expr": "(node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 685 },
     "targets": [
      {
       "expr": "(node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 562 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "IO - Disk Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate IO Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1778 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Ethernet Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Ethernet Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1948 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(node_network_receive_bytes_total[$__rate_interval])))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(sum by (instance) (rate(node_network_transmit_bytes_total[$__rate_interval])))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Infiniband Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Infiniband Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1788 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Received - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1796 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Received - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1796 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1804 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1804 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}