{
 "title": "Job - RMS",
 "tags": [ "omnistat" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "jobid",
    "label": "Job ID",
    "query": {
     "query": "label_values(rmsjob_info,jobid)"
    }
   },
   { "name": "interval", "label": "Resolution", "query": "5s,15s,30s,60s" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "Job Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$jobid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "{{batchflag}}"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rocm_num_gpus * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "max(timestamp(rmsjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GPU",
   "type": "stat",
   "description": "Average over time of the average GPU Utilization of all GPUs.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all GPUs in all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "stat",
   "description": "Average over time of the average of GPU Memory utilization of all GPUs.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all GPUs in all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "description": "Average over time of the average 1m Load Average of all nodes.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_load1 * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(node_load1 * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "stat",
   "description": "Average over time of the average memory utilization of all nodes.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(100 * ((node_memory_MemTotal_bytes  -node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 * ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "stat",
   "description": "Aggregate network bandwidth of all nodes. Includes received and transmitted data.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))) + sum(rate(node_network_transmit_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Ethernet"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))) + sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Infiniband"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]) * on (instance) group_left()(label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Eth Rx"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[$__rate_interval]) * on (instance) group_left()(label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Eth Tx"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "IB Rx"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "IB Tx"
    }
   ]
  },
  {
   "title": "GPU Usage - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 741 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 910 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 910 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 921 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - GPU IDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean GPU Utilization (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 28 },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "Max GPU Memory Utilization (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 676 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 676 },
     "targets": [
      {
       "expr": "avg by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 684 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - Distribution - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution of GPU Utilization Over Time (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "quantile(0.20, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.2 "
      },
      {
       "expr": "quantile(0.5, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Median"
      },
      {
       "expr": "quantile(0.8, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.8"
      },
      {
       "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per GPU",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per GPU",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Utilization per GPU",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - Distribution -  Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution of Average Utilization per Node",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 333 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per Node",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 333 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Utilization per Node",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 342 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Telemetry: GPU IDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 448 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (card, location) (rocm_temperature_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}} ({{location}})"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (card, location) (rocm_temperature_memory_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}} ({{location}})"
      }
     ]
    },
    {
     "title": "GPU Power (W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 464 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_average_socket_power_watts * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Engine Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 472 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_sclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Memory Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 472 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_mclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - 1m Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 497 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(node_load1) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Main Memory - Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 497 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage - Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - 1m Load Average - Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 506 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(node_load1 * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Main Memory - Utilization (%) - Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 506 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100 * ((node_memory_MemTotal_bytes  -node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth - Ethernet - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Bandwidth - Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth - Infiniband - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infiniband Bandwidth - Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1281 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1281 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Bandwidth - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO - Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1290 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IO - Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1290 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Annotated Regions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1729 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(count by (marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (marker) (avg by (instance) (rocm_utilization_percentage) * on (instance) group_left(jobid,marker) rmsjob_info{jobid=\"$jobid\"} * on (jobid) group_left(marker) count by (jobid,marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}