{
 "title": "slurm-global",
 "tags": [ "omnistat" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Active Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rmsjob_info{jobid=~\"^\\\\d+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active Batch Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Number of Jobs Running During Timeframe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count by (jobid) (rmsjob_info{jobid=~\"^\\\\d.+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active GPUs",
   "type": "stat",
   "description": "Number of GPUs in nodes allocated to active jobs.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage * on (instance) group_left() (rmsjob_info{jobid=~\"^\\\\d+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs - Rankings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Occupancy (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Occupancy (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 5, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 7, "x": 10, "y": 10 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 10 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU 1m Load Average (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (user,jobid) (node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Index",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "timestamp(group by (jobid,user,batchflag,partition,nodes) (rmsjob_info{jobid=~\"^\\\\d+\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Characterization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Core vs Memory per Job - Batch (1 min or longer)",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rocm_utilization_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "rocm_vram_used_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(group by (jobid,user) (rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Duration Histogram - Batch",
     "type": "histogram",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(group by (jobid) (rmsjob_info{jobid=~\"^\\\\d+\", batchflag=\"1\"}))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
       "legendFormat": "GPU"
      },
      {
       "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
       "legendFormat": "GPU Memory"
      }
     ]
    },
    {
     "title": "GPU Utilization by Node",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_edge_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_edge_celsius) * on (instance) (rmsjob_info{jobid=~\"^\\\\d+\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_edge_celsius) * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 1m Load Average per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Node: {{instance}}" }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "(node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "(node_load1 * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infiniband Bandwidth - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum((sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum((sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Received - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Received - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=~\"^\\\\d+\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) group_left(jobid,user) (label_replace(rmsjob_info{jobid=\"\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}