{
 "title": "standalone-global",
 "tags": [ "omnistat" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(rocm_num_gpus)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "description": "Average 1m Load Average.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_load1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network: Infiniband",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "IO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Models",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Driver",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU VBIOS",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Omnistat Schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "GPU - Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 769 },
     "targets": [
      {
       "expr": "avg(rocm_utilization_percentage)",
       "legendFormat": "GPU"
      },
      { "expr": "avg(rocm_vram_used_percentage)", "legendFormat": "GPU Memory Capacity" },
      { "expr": "avg(rocm_vram_busy_percentage)", "legendFormat": "GPU Memory Controller Activity" }
     ]
    },
    {
     "title": "GPU Utilization by Node",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1174 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2050 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU HBM Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2361 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_hbm_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 771 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(rocm_average_socket_power_watts) ",
       "legendFormat": "Power"
      }
     ]
    },
    {
     "title": "GPU Power per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 938 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_sclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Frequency per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_mclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Throttling Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Throttling Events per 1m",
     "type": "timeseries",
     "description": "Aggregating all throttling events in a node.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 191 },
     "targets": [
      {
       "expr": "sum by (instance) (delta(rocm_throttle_events[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "# of Throttling Events per Node",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_throttle_events)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 1m Load Average per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 209 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Node: {{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "IO - Disk Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate IO Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Ethernet Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Ethernet Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(node_network_receive_bytes_total[$__rate_interval])))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(sum by (instance) (rate(node_network_transmit_bytes_total[$__rate_interval])))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Infiniband Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Infiniband Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2001 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  }
 ]
}