{
 "title": "standalone-node",
 "tags": [ "omnistat" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" },
   { "name": "omnistat_exporter_port", "query": "8000" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(rocm_num_gpus,instance)"
    }
   },
   { "name": "instance", "query": "$node:$omnistat_exporter_port" }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rocm_utilization_percentage{instance=\"$instance\"}",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Utlization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rocm_utilization_percentage{instance=\"$instance\"})",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utlization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rocm_vram_used_percentage{instance=\"$instance\"}",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(rocm_average_socket_power_watts{instance=\"$instance\"}) ",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(rocm_temperature_celsius{instance=\"$instance\"}) ",
     "legendFormat": "Card: {{card}}"
    }
   ]
  },
  {
   "title": "GPU Throttling  - # of events observed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rocm_throttle_events{instance=\"$instance\"}",
     "legendFormat": "Card: {{card}}"
    }
   ]
  }
 ]
}