{
 "title": "standalone",
 "tags": [ "omnistat" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "stat",
   "description": "Number of GPUs with a utilization higher than 1%.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage > 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Usage - Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
       "legendFormat": "GPU"
      },
      {
       "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
       "legendFormat": "GPU Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Utilization by Node",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 130 },
     "targets": [
      { "expr": "rocm_utilization_percentage", "legendFormat": "{{instance}}, {{card}}" }
     ]
    }
   ]
  },
  {
   "title": "GPU Temperature - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Power - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Power - GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 1m Load Average per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Node: {{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth - Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infiniband Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  }
 ]
}