name: Formatting

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black isort
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: black format
      run: |
        black --diff --check .
    - name: Run isort formatter
      uses: isort/isort-action@master

  python-bytecode:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: find-bytecode
      run: |
        set +e
        FILES=$(find . -type f | egrep '__pycache__|\.pyc$')
        if [ -n "${FILES}" ]; then
          echo -e "\nError! Python bytecode included in commit\n"
          echo -e "### FILES: ###"
          echo -e "${FILES}"
          echo -e "##############"
          exit 1
        fi
