name: Unit
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: pip3 install -r requirements.txt -r test/requirements.txt
      - name: Run unit tests
        run: pytest -v test/test_unit_trace.py
